### ISSUE TITLE
Missing 'validate.wav' and 'train.wav'

### ISSUE THREAD

**Issue by abishekk92** [usernaamee/keras-wavenet#3]
The code assumes that `validate.wav` and `train.wav` are in the same folder, however, they are not shared as part of the repo. It would be great if a sample dataset or steps acquire one can be added.

**Comment by usernaamee** [comment]
Sorry, files are too large to upload.
I am using the [Librispeech dataset](http://www.openslr.org/12/).
I have concatenated all audio files in dev-clean to create train.wav and all files in test-clean to create validate.wav. I have resampled the audio files to 8000 Hz. I am still running test to figure out best network architecture.

**Comment by darinc** [comment]
Here is one method of concatenating the audio files after the appropriate Librispeech dataset is downloaded and unzipped (on Linux with VLC installed):

```
cvlc -vvv --sout-keep --sout-all --sout "#gather:transcode{acodec=s16l,channels=1,samplerate=8000}:std{access=file,mux=wav,dst=validate.wav}" `find LibriSpeech/test-clean/ -name "*.flac"` vlc://quit
cvlc -vvv --sout-keep --sout-all --sout "#gather:transcode{acodec=s16l,channels=1,samplerate=8000}:std{access=file,mux=wav,dst=train.wav}" `find LibriSpeech/dev-clean/ -name "*.flac"` vlc://quit
```

**Comment by abishekk92** [comment]
@usernaamee Thanks this is helpful. May be you can add the link in README?

**Comment by usernaamee** [comment]
Added link and @darinc 's concatenation trick audio in README.
