### ISSUE TITLE
Atrous Rate illegal for TF Backend

### ISSUE THREAD

**Issue by bhtucker** [usernaamee/keras-wavenet#6]
Hi,

I tried to run this today with Tensorflow as the backend. 

Using TF, the atrous rate must be a symmetric tuple (ie, (2, 2)):
https://github.com/usernaamee/keras-wavenet/blob/master/simple-generative-model-regressor.py#L15

**Comment by usernaamee** [comment]
Thanks for pointing that out, I fixed it now.
