### ISSUE TITLE
Did you implement the causal convolution part mentioned in the WaveNet paper?

### ISSUE THREAD

**Issue by zizyzhang** [usernaamee/keras-wavenet#9]
I noticed that you are using 'AtrousConvolution1D' in the WaveNet block, but is this function also implement causal convolution? Thx.

**Comment by usernaamee** [comment]
Actually, it has to be atrous as well as causal. Atrous (dilated) convolution is the powerful idea which makes it possible to train wavenet by significantly reducing the number of parameters.
